# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 30

[[main]]
  name = "Projects"
  url = "/project"
  weight = 40

[[main]]
  name = "Posts"
  url = "/post"
  weight = 50

[[main]]
  name = "PhenoCopter"
  url = "https://phenocopter.csiro.au"
  weight = 60
  hrefTargetBlank = true
[[main]]
  name = "R Packages"
  url = "#"
  weight = 61
  identifier = "rpackages"
[[main]]
  name = "RApsimNG"
  parent = "rpackages"
  identifier = "rapsimng"
  url = "https://rapsimng.bangyou.me/"
  hrefTargetBlank = true
[[main]]
  name = "WeaAna"
  parent = "rpackages"
  identifier = "weaana"
  url = "https://weaana.bangyou.me/"
  hrefTargetBlank = true
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70
