baseurl = "https://www.bangyou.me/"  # End your URL with a `/` trailing slash.
title = "Bangyou Zheng"
copyright = "&copy; 2017 Bangyou Zheng"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-106612662-2"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Bangyou Zheng"
  role = "Research scientist"
  organization = "CSIRO"
  organization_url = ""
  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "bz.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "Bangyou.Zheng@csiro.au"
  address = "306 Carmody Road, St Lucia, QLD"
  phone = "+61 7 3214 2620"
  date_format = "Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  highlight = true
  highlight_languages = []
  highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/
[[params.social]]
    icon = "home"
    icon_pack = "fa"
    link = "http://people-my.csiro.au/Z/B/Bangyou-Zheng"

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:Bangyou.Zheng@csiro.au"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/BangyouZheng"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com.au/citations?user=MfZ-QtEAAAAJ&hl=en"
  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Bangyou_Zheng"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/byzheng"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1



[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 2


[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 3


[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "AgData blog"
  url = "https://agdata.bangyou.me"
  weight = 5


[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

